services:
  api:
    build:
      context: ../
      dockerfile: .docker/app/Dockerfile
      target: dev
    environment:
      - IS_DOCKER=true
      - NODE_ENV=dev
    env_file:
      - ../.env.dev
    command: >
      sh -c "
      npm uninstall bcrypt &&
      npm install bcrypt &&
      npm run start:dev
      "
    volumes:
      - ../:/app
      - node_modules:/app/node_modules
    labels:
      - com.host.description=dev
    # depends_on:
    #   - db

volumes:
  node_modules:
